name: Создаем exe

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Скачиваем код
        uses: actions/checkout@v2

      - name: Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Устанавливаем зависимости
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Собираем exe
        run: |
          pyinstaller --noconfirm --onefile app.py

      - name: Загружаем результат в релиз
        uses: softprops/action-gh-release@v1
        with:
          files: dist/app.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
